export const FETCH_START = 'FETCH_START';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const TOGGLE_START_POPUP = 'TOGGLE_START_POPUP';
export const TOGGLE_FINISH_POPUP = 'TOGGLE_FINISH_POPUP';
export const TIMER_TICK = 'TIMER_TICK';
